### ISSUE TITLE
[v2.0, K584core] swprintf usage

### ISSUE THREAD

**Issue by danil-kondr2016** [kodemeister/X584#12]
As I know, the `swprintf` function has an argument after buffer which specifies the size of buffer (see [documentation](https://cplusplus.com/reference/cwchar/swprintf/)) but we don't know what size each buffer has. It seems that it is necessary to introduce argument like `size_t BufferSize` inside methods like `Format(unsigned MI, wchar_t *Str, bool FormatALU, bool FormatReg, bool ShowCarry)` to comply with C standard, isn't it?

On `bcc32` this code has been successfully compiles and instructions are formatted properly, but I think that if we'll use modern `bcc32c`  clang-based compiler, it will complain about swprintf.

**Comment by danil-kondr2016** [comment]
Oh, this is non-standard swprintf without length argument provided by Embarcadero )(<https://docwiki.embarcadero.com/RADStudio/Sydney/en/Sprintf,_swprintf>)

**Comment by kodemeister** [comment]
Yes, this function is provided by VCL like `AnsiUpperCase` and other global functions. It helps to mechanically migrate old code to Unicode by simply replacing `char`-based functions with their wide character counterparts. There is nothing wrong with using it. Let's reopen this issue if there will be any issues with Clang-based compilers in future.

**Comment by danil-kondr2016** [comment]
There is `_swprintf` function which available in Windows' C standard library (https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/sprintf-sprintf-l-swprintf-swprintf-l-swprintf-l?view=msvc-170) and it seems that we can just replace invalid Embarcadero's `swprintf` with `_swprintf`.
