### ISSUE TITLE
[v2.0, Main] CodeListView behavior on modern platforms

### ISSUE THREAD

**Issue by danil-kondr2016** [kodemeister/X584#15]
It seems that modern list view which supplied by Common Controls 6.10 and higher hooks some mouse events to fill an element with hover block so selecting two or more element by mouse doesn't work.

Another side-effect is some drawing issues when hovering lines of code in CodeListView.

**Comment by danil-kondr2016** [comment]
So, I think that this issue is tightly linked with way of selection of elements in `CodeListView`:
1. `CodeListView` doesn't support multiple selection by itself since its property of `MultiSelect` is `false`.
2. Selection is keeped by `SelCount` field of `TX584Form` and `CodeListView->ItemFocused->Index` property. It seems that list view inside Common Controls 5.0 doesn't change focused item but Common Controls 6.10 does so multiple selection with mouse is not possible.

`TListView` provides its own way to retrieve selected items if `MultiSelect` is `true`. It has property `CodeListView->Selected` which holds first selected item of the list view. Each subsequent element can be retrieved by calling method `CodeListView->GetNextItem(CurrentItem, sdAll, isSelected)`. But using this method of selecting requires more careful handling of selected non-adjacent lines of code for deleting.

**Comment by kodemeister** [comment]
I don't remember why I disabled built-in `MultiSelect` property and implemented a custom multi-selection approach using `CodeListView->ItemFocused->Index` and `SelCount`. Probably I didn't want users to select non-consecutive rows using Ctrl+Click. It's unclear how to properly implement Copy and Paste in this case. Say, the user selected lines 0, 2, 4 and pasted them somewhere. Should we paste lines as they are, or maybe collapse them into consecutive microinstructions? What to do if Insert mode is active? So I probably didn't want to mess with all this stuff and forced users to always select consecutive rows.

**Comment by danil-kondr2016** [comment]
I think that we should collapse lines into consecutive microinstructions like in Excel:

https://github.com/user-attachments/assets/543fd625-d956-4169-bdaa-40b3605fd2f5

I think that this is an conventional way of handling this behavior.

**Comment by danil-kondr2016** [comment]
But if we delete two or more non-consecutive lines I think that there should be some kind of tricky algorithm to resolve this situation optimally

**Comment by kodemeister** [comment]
> I think that we should collapse lines into consecutive microinstructions like in Excel:

Okay. Sounds fair enough.

> But if we delete two or more non-consecutive lines I think that there should be some kind of tricky algorithm to resolve this situation optimally

Yes, deletion of non-consecutive items is not very trivial, especially if one needs an in-place algorithm. The simplest approach is similar to the existing implementation in #30. That is, create a temporary array of pairs (`std::vector<std::pair<unsigned, UnicodeString>>`), copy all non-selected items to it, pad with NOPs to 1024 items in total and finally copy everything back to `CodeListView`. This is not the fastest solution but we don't need any performance anyway.

**Comment by danil-kondr2016** [comment]
I proposed a way of handling this in #30 which is as optimal as your but I think that there's another way to handle this.
We can link opcode of instruction with `CodeListView` item, remove it and strip/pad to 1024 items by NOP items. But this way can lead to increase amount of code needed to address opcodes from `CodeListView` items.

**Comment by kodemeister** [comment]
Fixed by #30.
