### ISSUE TITLE
Help format

### ISSUE THREAD

**Issue by danil-kondr2016** [kodemeister/X584#2]
Original help is written in DOC format which shows differently on different versions of Microsoft Word 2003. I think that we should convert it to CHM format which shows reliably on Windows platforms.

**Comment by kodemeister** [comment]
Yeah, it would be nice to provide docs in more reliable and non-editable format, such as CHM. PDF would be even better but unfortunately it is not supported out of the box. In any case, PRs are welcome :grin:

**Comment by kodemeister** [comment]
Implemented in #4
