### ISSUE TITLE
[v2.0] New column for control flow statements

### ISSUE THREAD

**Issue by kodemeister** [kodemeister/X584#21]
For now we cannot have both control flow statements and ordinary comments per single microinstruction. It would be nice to display a separate column exclusively for control flow statements.

![375482685-c8fbc4fe-c61c-4805-9274-89bf31e6c3db](https://github.com/user-attachments/assets/b2babdf4-8de2-4c9b-9156-65db064efbec)

To keep the backward compatibility with old `.x584` file format, we can store both control flow statements and ordinary comments in the existing comment field but separate them with any reserved character, such as `\n`. We should check for presence of this separator while loading each comment from `.x584` file. The following flowchart illustrates the possible parsing logic:

![Comment Parsing](https://github.com/user-attachments/assets/effe4c98-6f59-4467-b2ce-68eb63b6fc76)

The total length of (control flow statement + comment + separator) shouldn't exceed 255 characters due to `.x584` format restrictions. We need to properly limit the number of entered characters in `InputEdit`. Control flow operators shouldn't take more than a few dozen characters. The rest of available characters can be safely used for comments.

**Comment by kodemeister** [comment]
If you don't like to use a special separator, there is actually another way to extend `.x584` format. Just append any v2.0 data to the end of file.

* Old 1.x versions will read the first 1024 rows from the file and ignore the rest.
* New 2.x versions can take advantage of extra data beyond 1024 rows.

For example, you can append all control flow statements in UTF-8 encoding to the end of file. Or even append both control flow statements and ordinary comments, if you wish to store everything in Unicode. However, old comments in CP1251 encoding still need to be kept in the first 1024 rows for backward compatibility.

**Comment by danil-kondr2016** [comment]
This variant is better since if some kind of separator like '\n' is present comment is not a control operator

**Comment by kodemeister** [comment]
Implemented in #36.
