### ISSUE TITLE
[v2.0] Alternative English names for K584VM1 outputs

### ISSUE THREAD

**Issue by kodemeister** [kodemeister/X584#22]
The `if` control flow statement currently uses Russian names for K584VM1 outputs, such as `ПАЛУ0` or `!СДЛ1`. We can additionally provide their English equivalents like `ALUCOUT` from the K584VM1 datasheet:

http://www.155la3.ru/datafiles/k584vm1.pdf

**Comment by kodemeister** [comment]
Oh, I completely missed that our CHM file also provides English names for K584VM1 outputs! We have to use names from CHM file instead of [K584VM1 datasheet](http://www.155la3.ru/datafiles/k584vm1.pdf) because we ship the former together with the application. Sorry for the confusion!

Please check the suggested table against CHM file. Does this look right to you?

| Russian | Russian Alt | English | English Alt |
| ------- | ----------- | ------- | ----------- |
| ПАЛУ3   | П           | CO3     | C           |
| !СДЛ1   | !СДЛ1       | !SL1    | !SL1        |
| !СДП1   | !СДП1       | !SR1    | !SR1        |
| !СДЛ2   | !СДЛ2       | !SL2    | !SL2        |
| !СДП2   | !СДП2       | !SR2    | !SR2        |
| РРР0    | РРР0        | XWR0    | XWR0        |
| РРР3    | РРР3        | XWR3    | XWR3        |
| A15     | А15         | A15     | A15         |
| B15     | В15         | B15     | B15         |
| ПАЛУ0   | П0          | CO0     | C0          |
| ПАЛУ1   | П1          | CO1     | C1          |
| ПАЛУ2   | П2          | CO2     | C2          |

**Comment by danil-kondr2016** [comment]
Yes, I forgot about CHM

**Comment by kodemeister** [comment]
Fixed by #37.
