### ISSUE TITLE
[v2.0] Should we subclass CodeListView as TCodeList or something like that?

### ISSUE THREAD

**Issue by danil-kondr2016** [kodemeister/X584#27]
Since `CodeListView`'s behavior is difficult and very specific and it is linked with code data inside it should we separate its logic and data inside its own subclass like `TCodeList` or something like that?

**Comment by kodemeister** [comment]
Honestly, I would avoid to rewrite existing code unless absolutely necessary. In fact, we only need to fix two things in `CodeListView` to make it work well:
1. Disable the default selection and hovering with mouse. Or, at least, hide them from the user. Probably, overriding the default painting mechanism could help. See `OnAdvancedCustomDraw` and so on.
2. Make Shift+Click work again, maybe with some sort of hack.
