### ISSUE TITLE
[v2.0] Copying to clipboard doesn't work for the first time

### ISSUE THREAD

**Issue by kodemeister** [kodemeister/X584#31]
Steps to reproduce:

1. Open any text editor and copy some text to the clipboard.
2. Run app and make sure Paste button is disabled.
3. Click Copy button.
4. Observe that Paste button quickly flashes and gets disabled again.
5. Click Copy button once more.
6. Observe that selection is finally copied to the clipboard.

**Comment by danil-kondr2016** [comment]
So I tried to reproduce this bug and I can't reproduce it. At step 4 Paste button doesn't flash quickly and get disabled, it stays enabled

**Comment by danil-kondr2016** [comment]
Windows 10 Pro, bug has not been reproduced

**Comment by kodemeister** [comment]
Hmm, strange. I can easily reproduce this on Windows 11. Once I click Copy button, the Paste button is deliberately enabled in `CopyItemClick`. However, after a fraction of a second the `OnClipboard` handler is triggered and then it disables Paste button again.

[bug.webm](https://github.com/user-attachments/assets/043dffcc-a4de-411b-89c7-1d3bbbffac40)

**Comment by danil-kondr2016** [comment]
Agree. It's very strange.

https://github.com/user-attachments/assets/e901b00f-9d3f-470f-8805-f37661690457

It seems that somebody writes something into the clipboard and our command clears.

**Comment by danil-kondr2016** [comment]
Try add `Clipboard()->Open()` and `Clipboard()->Close()` calls at the bounds of `GetFromClipboard` and `PutIntoClipboard`, I don't know why this bug occurs

**Comment by danil-kondr2016** [comment]
> Hmm, strange. I can easily reproduce this on Windows 11. Once I click Copy button, the Paste button is deliberately enabled in `CopyItemClick`. However, after a fraction of a second the `OnClipboard` handler is triggered and then it disables Paste button again.
> 
>  bug.webm

I tried even disable enabling paste button in `CopyItemClick` and this bug doesn't reproduce!

**Comment by danil-kondr2016** [comment]
I recommend to monitor clipboard contents: <https://www.nirsoft.net/utils/inside_clipboard.html>. Check Options - Refresh On Clipboard Change

**Comment by kodemeister** [comment]
Ok, got it. I'm running Windows 11 in QEMU virtual machine. The issue seems to be related to guest tools, namely Spice Agent that shares Windows clipboard with the host. Stopping Spice Agent service resolves the issue.
