### ISSUE TITLE
[v2.0] Semantic versioning

### ISSUE THREAD

**Issue by danil-kondr2016** [kodemeister/X584#40]
I have merged all pending pull-requests into my branch and compile my beta versions which called 2.0.0-beta.X where X is number of build. Should we specify versions in such way for 2.x versions of X584?

**Comment by kodemeister** [comment]
From my experience, small hobby projects rarely need SemVer. A lot of them stuck forever on version 1.0.0 and never get updated. I don't see much reason to make "patch" releases or "hotfixes" or whatever they call it. Most likely there will be a few more releases for the next decade, such as 2.0, 2.1, 2.2, and that's all.
