### ISSUE TITLE
[v2.0] Width of ВхПАЛУ

### ISSUE THREAD

**Issue by danil-kondr2016** [kodemeister/X584#43]
![image](https://github.com/user-attachments/assets/cc4a05e5-2a44-455c-9fa7-79b1fc176a48)

**Comment by kodemeister** [comment]
Please check the latest commit. Does `ВхПАЛУ` look better now? No more horizontal scrollbar in the code editor?

**Comment by danil-kondr2016** [comment]
![image](https://github.com/user-attachments/assets/92df9e3e-8b13-4d26-ac31-873706465bcc)
100%

**Comment by kodemeister** [comment]
That's strange, 125% is displayed fine for me. The width of ВхПАЛУ was increased from 55 to 60 pixels and this still seems not enough. Does 65 pixels work for you?

**Comment by danil-kondr2016** [comment]
70 pixels is OK on 100% and 125%

**Comment by danil-kondr2016** [comment]
![image](https://github.com/user-attachments/assets/f3cd3dc0-108e-4fbb-a230-87fee60fef08)

But on 100% it looks like not so nice.

**Comment by danil-kondr2016** [comment]
It seems that width of this column should be dependent on DPI settings

**Comment by danil-kondr2016** [comment]
60 pixels is OK for 100%, 70 - for 125%

**Comment by danil-kondr2016** [comment]
Check out #44

**Comment by kodemeister** [comment]
I honestly don't see any difference between #44 and hardcoding the column width to 58 pixels but if that pull request works better for you, we're good to go :smile:
