### ISSUE TITLE
"Access violation at address 00407705 in module 'X584.exe'. Read of address 00000008." when removing multiple selected elements

### ISSUE THREAD

**Issue by danil-kondr2016** [kodemeister/X584#6]
When I created a project in X584 and tried to clear multiple selected instructions, the "Access violation..." error pops out and instructions are not removed.
![X584 error](https://github.com/user-attachments/assets/72d2d6ab-4fad-434f-a455-459fdbd0aa66)

**Comment by danil-kondr2016** [comment]
It seems that `CodeListView->ItemIndex == -1` if two or more elements are selected.

**Comment by kodemeister** [comment]
Fixed by #8
